### ISSUE TITLE
打包后页面报错

### ISSUE THREAD

**Issue by qq1255198035** [chenjun1127/react-antd-admin#2]
Super expression must either be null or a function

能解决一下吗？

**Comment by fzp0723** [comment]
同问

**Comment by fzp0723** [comment]
> Super expression must either be null or a function
> 
> 能解决一下吗？

Login.js 里面的 particles 组件打包后会报错，把相关代码都注释就好了，但是不知道怎么修复。。。

**Comment by hellovveb** [comment]
> Super expression must either be null or a function
> 
> 能解决一下吗？

我做一个新平台，页面不是很多，想尝试用react做开发，结果接口都调试好了，打包发布到线上后报错了，然后重新把所有的引用升级到最新版本，就可以了

**Comment by liangfenggithub** [comment]
将 react-particles-js 升级到 3.2.1 版本即可解决打包错误问题。

**Comment by chenjun1127** [comment]
版本问题，参考5楼答案
